name: Unit Testing

on:
  pull_request:
    branches: [dev]
  push:
    branches: [test]

jobs:
  unit_testing:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project dependencies, if any

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests
